version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: mkdir -p ~/reports
      - run: node --version
      - run: npm --version
      - run: env
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install tap-xunit
            - run: npm test | tap-xunit > ~/reports/test.xml
            - run: npm run build
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports  

workflows:
    build-and-test:
      jobs:
        - build-and-test